### ISSUE TITLE
M. Miller Comments on PDDI doc

### ISSUE THREAD

**Issue by abwiggins** [w3c/hcls-drug-drug-interaction#10]
MMiller:

- [x] in section 1) a range is given, 'occur in 5.3% - 14.3% of inpatients', why the range? 
      **RESOLVED: the range is defined from https://www.ncbi.nlm.nih.gov/pubmed/22022824** Also, changed the sentence to read "Clinically important events attributable to PDDI exposure have been identified in multiple studies, with rates ranging from  5.3% - 14.3% of inpatients, and up to 231,000 emergency department visits each year in  the United States alone [[magro-2012]][[cdc-faststats]]." 
- [x] its odd to me that in section 2) that 'drugs involved' is given second class citizenship just because it wasn't defined by users.  this section, i think, should simply list all the definitions. 
      **Being addressed and will be brought up during call on 06/21/2018**
- [ ] in section 2.1: 'drugs involved' SHOULD be listed as sets of terms from a terminology such as...'.  is there anywhere to list which terminology a term is from?  otherwise the reader is left to guess/search terminologies for the term 
  **TODO**

**Comment by abwiggins** [comment]
YHe:
[PDDI-min-info-model-community-group-note-draft-YongqunHe.docx](https://github.com/w3c/hcls-drug-drug-interaction/files/2059632/PDDI-min-info-model-community-group-note-draft-YongqunHe.docx)

**Comment by abwiggins** [comment]
XJing:
[PDDI-Min-Info-Model-Community-Group-Note-draft-XiaJing.docx](https://github.com/w3c/hcls-drug-drug-interaction/files/2059637/PDDI-Min-Info-Model-Community-Group-Note-draft-XiaJing.docx)

**Comment by abwiggins** [comment]
JHorn:
[PDDI-Min-Info-Model-Community-Group-Note-draft-JohnHorn.docx](https://github.com/w3c/hcls-drug-drug-interaction/files/2059642/PDDI-Min-Info-Model-Community-Group-Note-draft-JohnHorn.docx)

**Comment by abwiggins** [comment]
DMalone:
[PDDI-min-info-model-community-group-note-draft-DanMalone.docx](https://github.com/w3c/hcls-drug-drug-interaction/files/2059647/PDDI-min-info-model-community-group-note-draft-DanMalone.docx)

**Comment by abwiggins** [comment]
BLebaron:
[PDDI-min-info-model-community-group-note-draft-BrianLeBaron.docx](https://github.com/w3c/hcls-drug-drug-interaction/files/2059649/PDDI-min-info-model-community-group-note-draft-BrianLeBaron.docx)

**Comment by rkboyce** [comment]
To address the last comment - we plan to write a small section about concept/value sets and refer to it in the examples. I have referred to this issue in the W3C note draft where it is marked with a pink background to indicate further work is underway.

**Comment by rkboyce** [comment]
done
