### ISSUE TITLE
Addressing serious/severity in the Note

### ISSUE THREAD

**Issue by rkboyce** [w3c/hcls-drug-drug-interaction#12]
There is dissatisfaction across the task force with the distinction of the terms "serious" and "severe" which has led us to see an alternative approach to conveying the importance of the PDDI. A number of suggestions have been made including keeping the terms but specifying them better (e.g., using a 2X2 table with examples of each combination including negation), using different words like 'morbidity' and 'mortality' or 'criticality' (which aligns with other efforts), keeping  dropping them entirely, using operational terms that suggest the priority of the action (e.g., 'no action needed', 'monitor at take action as necessary', and 'avoid'). The team decided to move forward with some polling about the options using a questionnaire the presents the original use cases for the terms and presents each option with background. This questionnaire will be sent out in early July.

**Comment by jodischneider** [comment]
See also #3
