### ISSUE TITLE
Figure 1, "Structured Product Labeling" should make clear how general/specific it is.

### ISSUE THREAD

**Issue by jodischneider** [w3c/hcls-drug-drug-interaction#23]
It's not immediately clear whether refers to "Structured Product Labeling" package inserts in general, the FDA labeling, or the HL7 standard, etc. This is particularly confusing since "Summary of Product Characteristics" is used in some countries. 

Consider "product labeling", which  is used as the generic term in 5.2.

**Comment by rkboyce** [comment]
I don't think this is a concern for the portion of the audience that  understands labeling. SPCs are not structured and "extensions" is a common term to describe an enhancement to the standard that would be applicable to instances that use the standard.  Also, the related paper will be able to expand further on this
