### ISSUE TITLE
explicit vs. implicit statement of formulation (3.1)

### ISSUE THREAD

**Issue by jodischneider** [w3c/hcls-drug-drug-interaction#32]
This sentence doesn't make sense to me. I'd expect either "even implicitly" or "explicitly" just before the colon
"However, this constraint on the applicability of this PDDI is not stated implicitly: the formulation of the NSAID being described is ambiguous, and the importance of the means of administration is implied, but not stated directly."

**Comment by rkboyce** [comment]
fixed
