### ISSUE TITLE
Transition/narrative needed in 3.2 to indicate that the user stories follow and that this is an introduction

### ISSUE THREAD

**Issue by jodischneider** [w3c/hcls-drug-drug-interaction#34]
I found 3.2 really jarring -- with the links, I thought maybe I should follow each of them, and I didn't realize that they were below in the text. Maybe some of "Three user stories focused on the critical process of medication reconciliation for PDDIS detailed in the Appendix (see B.1.1.2 Decision Trees Created for the Minimum Information Model Domain Analysis) are given here; remaining user stories are located in B.1.2.2 User stories for the minimum information model." should go sooner, before the list? Any indication that this is an introduction could help.

Also, are there really 12 stories? I count 10 from the listing (including the 3 with the physician user).

Consider deleting the section reference since section 3.3 is the immediate next section. Also consider moving the mention of color coding into 3.3 itself: "Each user story was color coded for mention of core information items in the minimum information model (see 3.3 Color codes used in user stories)."

**Comment by jodischneider** [comment]
I'm also not sure how 3.2 and 5 are supposed to relate. Section 5 seems to have more introductory content, which is odd for a discussion section.

**Comment by rkboyce** [comment]
Ya, this was rough. Made several changes to address.
