### ISSUE TITLE
Example of information content entities could be suppressed

### ISSUE THREAD

**Issue by jodischneider** [w3c/hcls-drug-drug-interaction#35]
I think this text could be suppressed:
"For example, the core term Mechanism of Interaction does not represent an entity that has participants or is preceded by another biological process. Those would be properties of material processes that would be invoved if the interaction were actually realized. Instead, the MPIO term Mechanism of Interaction is an information content entity provides information about those material processes. It is up to other ontologies, such as DIDEO or DINTO, to provide a detailed representation of the underlying biomedical processes, qualities, and material entities. These representations will be complementary to the core information items in MPIO."

If you keep it, consider a paragraph break to help the reader.

**Comment by rkboyce** [comment]
I removed it.
