### ISSUE TITLE
"This can include context parameters that currently might not available but that, if present, would be useful for increasing the specificity of the PDDI CDS alerts." (5.1)

### ISSUE THREAD

**Issue by jodischneider** [w3c/hcls-drug-drug-interaction#36]
This seems to me to undersell: isn't it the lack of specificity that is ALSO contributing to overalerting and alert fatigue from unnecessary alerts?

"This can include context parameters that currently might not available but that, if present, would be useful for increasing the specificity of the PDDI CDS alerts." (5.1)

**Comment by rkboyce** [comment]
will leave as is for now
